import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Toaster } from "sonner";
import {connectToDB} from "@/lib/connectToDB"
import {SessionProvider} from 'next-auth/react'
import { getServerSession, Session } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";

import Wrapper from "./Wrapper";




export const metadata: Metadata = {
  title: "Echo Anon",
  description: "Generated by create next app"
};
connectToDB()

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const session = await getServerSession(authOptions);
  return (
    <html lang="en" className="dark" >
      <Head>
        <link rel="icon" href="/favicon1.ico" />
      </Head>
      <body
      className="bg-slate-800 text-black dark:bg-zinc-950 dark:text-white flex flex-col h-screen"
      >
          <Wrapper session={session} >{children}</Wrapper>
          <Toaster toastOptions={{
            style:{
              color: 'rgb(30 41 59)',
              fontSize: '14px',
              padding: '10px',
              position: 'fixed',
              bottom: '10px',
            }
          }} />
      </body>
    </html>
  );
}
